### ISSUE TITLE
Don't pass Options to recurr_check

### ISSUE THREAD

**Issue by nickdrozd** [boydjohnson/lin-rado-turing#9]
Here is the current signature of `recurr_check`:

```rust
fn recurr_check(
        &mut self,
        step: usize,
        snapshots: Option<&mut Snapshots<S, Sym>>,
        deviations: Option<&Vec<i64>>,
        init: usize,
        beeps: &Beeps<S>,
        dev: i64,
    ) -> Option<Halt>
```

`snapshots` and `deviations` are both `Option`s that need to be
unwrapped in the function body. I think it would be cleaner to do that
unwrapping outside of the function body, and only call the function
once it's known that there really are snapshots and deviations to be
passed in. `recurr_check` is a complicated function, and saving some
indetation would make it easier to read.

In spirit this is along the lines of d7ad4f1. I would implement it
myself, but this change requires convincing the borrow checker, and I
really can't deal with the borrow checker.

**Comment by boydjohnson** [comment]
Sounds good. I'll implement the change.

**Comment by boydjohnson** [comment]
Take a look at #11 before it gets merged to make sure it meets your approval.

**Comment by boydjohnson** [comment]
#11 was merged so this looks to be taken care of.
